repositoryUrl: https://github.com/dynamsoft-docs/capture-vision-docs/blob/main
repository: Dynamsoft/capture-vision-docs
docFullPath: https://www.dynamsoft.com/capture-vision/docs/
firstLevelUrl: /capture-vision/docs/
docHomePage: /capture-vision/docs/introduction/

introduction: /capture-vision/docs/introduction/
architecture: /capture-vision/docs/architecture/
parameter: /capture-vision/docs/parameters/
parameterFile: /capture-vision/docs/parameters/file/
parameterReference: /capture-vision/docs/parameters/reference/

assets: /capture-vision/docs/assets/
edit_icon: /capture-vision/docs/assets/img-icon/edit-icon.png

useVersionTree: true

baseurl: "/capture-vision/docs"
plugins:
  - jemoji

url: "https://www.dynamsoft.com" # sitemap root

