# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the main branch
  #push:
   # branches: 
    #- main 
    #- preview 

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains jobs called "Build-main" and "Build-Preview"
  Build-main:
    if: ${{ github.ref == 'refs/heads/main' }}
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      #- uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          cd /home/ubuntu
          [ -d DCVDoc ] && rm -rf DCVDoc
          [ -d capture-vision-docs ] && rm -rf capture-vision-docs
          [ ! -d DCVDoc ] && mkdir -p DCVDoc
          [ ! -d capture-vision-docs ] && git clone --depth 1 https://github.com/dynamsoft-docs/capture-vision-docs.git
          [ ! -d Docs-Template-Repo-Preview ] && git clone --depth 1 --branch preview https://github.com/dynamsoft-docs/Docs-Template-Repo.git Docs-Template-Repo-Preview
          cd capture-vision-docs && git pull && cd .. && cp -rfp ./capture-vision-docs/* ./DCVDoc/
          cd Docs-Template-Repo-Preview && git pull && cd .. && cp -rfp ./Docs-Template-Repo-Preview/* ./DCVDoc/
          cd DCVDoc && bundle exec jekyll build --incremental

      - name: Sync files to Test Env
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_TEST_SITE_SERVER }}
          username: ${{ secrets.FTP_TEST_SITE_USER }}
          password: ${{ secrets.FTP_TEST_SITE_PASSWORD }}
          port: 7500 
          local-dir: /home/ubuntu/DCVDoc/_site/
          server-dir: /www.dynamsoft.com/capture-vision2/docs/

